apiVersion: v1
appVersion: 2.16.2.0-b41
description: YugabyteDB Anywhere provides deployment, orchestration, and monitoring
  for managing YugabyteDB clusters. YugabyteDB Anywhere can create a YugabyteDB cluster
  with multiple pods provided by Kubernetes or OpenShift and logically grouped together
  to form one logical distributed database.
home: https://www.yugabyte.com
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- email: ram@yugabyte.com
  name: Ram Sri
- email: arnav@yugabyte.com
  name: Arnav Agarwal
name: yugaware
version: 2.16.2
