apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-tester"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    helm.sh/hook: test-success
spec:
  containers:
  - name: tester
    image: "{{ .Values.tester.image }}"
    imagePullPolicy: Always
    volumeMounts:
    - name: config-volume
      mountPath: /tester
    command: ["bash"]
    args: ["/tester/run.sh"]
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APP_INSTANCE_NAME
      value: {{ .Release.Name }}
    - name: APP_SERVICE
      value: {{ .Release.Name }}-yugaware-ui
  restartPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-test"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/verification: test
data:
  run.sh: |-
    set -x
    ui="http://${APP_SERVICE}"
    echo GET $ui
    http_status_code=$(curl -o /dev/null -s -w "%{http_code}\n" $ui)
    echo "Expected http status code: 200"
    echo "Actual http status code: $http_status_code"
    if [[ "$http_status_code" == "200" ]]; then
      echo SUCCESS
    else
      echo FAILURE
      exit 1
    fi